-- bronze/stg__human_instructions_queue.sql
--
-- Thin staging wrapper over minkops_app.public.human_instructions_queue.
-- Pull-based work queue: humans post instructions, agents claim and execute.
-- Implements lease/retry semantics with priority ordering.
--
-- Transient OLTP locking columns (locked_at, locked_by, lease_expires_at)
-- are excluded — they reflect instantaneous worker state that is meaningless
-- once a row reaches the warehouse. All other lifecycle and RLHF signal
-- columns are preserved.

with source as (

    select * from {{ source('minkops_app', 'human_instructions_queue') }}

),

renamed as (

    select
        -- identifiers
        id                  as instruction_id,
        tenant_id,
        last_run_id,        -- most recent run spawned; retries may create multiple

        -- authorship and routing
        author_id,          -- human manager (email/handle)
        target_agent_id,    -- human's preference (hint, not enforced)
        target_role,
        assigned_agent_id,  -- resolved by planner at claim time
        assigned_by,
        assigned_at,

        -- content
        instruction,
        payload             as instruction_payload,  -- JSONB; structured input for the agent

        -- scheduling and priority
        priority,
        available_at,       -- earliest claimable time; used for backoff scheduling
        due_at,
        expires_at,

        -- lifecycle state
        status              as instruction_status,
        attempts,
        max_attempts,

        -- completion
        acknowledged_at,
        completed_at,
        completed_by,
        agent_response,     -- human-readable summary generated by the agent
        result_payload,     -- JSONB; structured output for dashboards / downstream automation

        -- RLHF training signal
        human_feedback,
        feedback_score,     -- 1–5 rating; NULL means not yet reviewed

        -- timestamps
        created_at          as instruction_created_at,
        updated_at          as instruction_updated_at,

        current_timestamp   as _loaded_at

    from source

)

select * from renamed
